config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => "custom_sessions" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  root "pages#home"
  get '/legal', to: "pages#legal"
  get '/profile', to: "pages#profile"
  # get  '/my-achievements', to: "pages#my_achievements"

  resources :goals, only: [:create, :show, :index]

  resources :matches, only: [:show, :edit, :update, :index, :create] do
    resources :tasks, only: [:new, :create, :index]
    resources :chatrooms, only: [:show, :create] do
      resources :messages, only: :create
    end
  end

  resources :tasks, only: [:edit, :update]
  resources :tasks, only: :destroy, as: :delete_task
  resources :goals, only: [:edit, :update]
  resources :goals, only: :destroy, as: :delete_goal
end

app/views/shared/_add-goal-modal.html.erb
  <button type="button" class="btn mt-2 w-100 white-background-shadow-blue-hover newgoal my-2" data-toggle="modal" data-target="#newGoalModalCenter">
    <i class="fa-solid fa-plus"></i> Create new goal
  </button>

  <!-- Modal -->
  <div class="modal fade" id="newGoalModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Create a new goal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= render "shared/new-goal" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner d-flex justify-content-center">
  <div class="d-flex flex-column ms-5 banner-text-container" >
    <h1 class="mb-4">Empowering Buddies, Achieving Dreams!</h1>
    <p>The ultimate accountability buddy for anyone striving to reach their goals! Whether it’s aiming to read more, hit the gym regularly, learn a new skill, or ace that course, <br>
       we've got you covered.</p>
    <div>
      <a class="btn btn-primary mt-3" href="users/sign_up" style= "font-size: 20px; padding: 15px 30px; border-radius: 5px"> Try for free!</a>
    </div>
  </div>
  <div class="image justify-self-end">
    <img src="<%= asset_path('winners.svg') %>" alt="Image Description" height="400" width="600">
  </div>
</div>

app/views/shared/_edit-goal-form.html.erb
<div class="">
  <div class="mt-4 listing-form" data-controller="filter-subcategory">
    <%= simple_form_for(goal) do |f| %>
      <%= f.input :category, as: :select, collection: Goal::CATEGORIES.keys,
                  input_html: { data: {action: "change->filter-subcategory#getKey"}
                  }%>
      <%= f.input :sub_category, as: :select, collection: [],
                  input_html: { data: {filter_subcategory_target: "subcategory"} }   %>
      <%= f.input :description, label: "Your goal description" %>
      <%= f.input :deadline  %>
      <%= f.label "Do you prefer meeting offline with your buddy, or online (or both)?", class: "py-3" %>
      <%= f.input :offline %>
      <%= f.input :online %>
      <%= f.submit "Edit goal", class: "btn btn-primary my-4"%>
    <% end %>
  </div>
</div>

app/views/shared/_edit-goal-modal.html.erb
<button type="button" class="btn btn-edit-goal" data-toggle="modal" data-target="#editGoalModalCenter-<%=goal.id%>">
  <i class="fas fa-pencil-alt"></i>
</button>

<!-- Modal -->
<div class="modal fade" id="editGoalModalCenter-<%=goal.id%>" tabindex="-1" role="dialog" aria-labelledby="editGoalModalCenter--<%=goal.id%>" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editgoaltitle">Edit goal</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "shared/edit-goal-form", goal: goal %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_edit-match-form.html.erb
<div class="">
  <div class="mt-4 listing-form">
    <%= simple_form_for @match do |f| %>
      <%= f.input :status, label: "Cancel your buddy match", as: :select, collection: Match::MATCH_STATUSES.reject { |category| category != "cancelled" }, :selected => "cancelled", html_input: "required" %>
      <%= f.input :cancel_reason, label: "Let us know why you're cancelling the match", as: :text, placeholder: "For example: My buddy doesn't respond." %>
      <%= f.submit class: "btn btn-primary mt-1 mb-4"%>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-light alert-dismissible fade show m-1 flash-alert-login" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-light alert-dismissible fade show m-1 flash-alert-login" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if info %>
<div data-controller="backdrop-alert">
  <div class="flash-alert-backdrop" role="alert" data-backdrop-alert-target="backdrop"></div>
  <div class="alert alert-light alert-dismissible fade show flash-alert-info" role="alert">
    <%= info %>
    <button type="button" class="btn-close" data-action="click->backdrop-alert#toggle" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
</div>
<% end %>

app/views/shared/_goal-card.html.erb
<% if goal.matched == false %>
  <div class="card w-100 mb-2 white-background-shadow" id="goal-card">
    <div class="card-body d-flex justify-content-between">
      <div class="pe-3">
        <div class="d-flex align-items-start">
          <h5 class="card-title d-flex align-items-center"><%="#{goal.category.capitalize} goal" %> </h5>
          <%# edit goal modal  %>
          <%= render "shared/edit-goal-modal", goal: goal %>
          <%# delete goal button  %>
          <%= link_to delete_goal_path(goal),
              data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "d-block" do %>
            <i data-feather="trash-2" class="trash-icon"></i>
          <% end %>
        </div>
        <p class="card-text"><%= goal.description %></p>
        <p><strong>Deadline: <%= goal.deadline %></strong></p>
      </div>
      <div class="d-flex flex-column justify-content-start">
        <%= simple_form_for @match do |f| %>
          <%= f.input :goal, as: :hidden, input_html: { value: goal.id } %>
          <%= f.submit "Match me!", class: "btn btn-primary match-button" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_match-card.html.erb
<div class="match-card card d-flex flex-row card w-100 mb-2 white-background-shadow align-items-center">

  <div class="ps-3 text-center">
    <% if current_user.photo.attached? %>
      <%= image_tag(current_user.photo, class: "avatar-bordered-medium-shadow", alt: "avatar") %>
    <% else %>
       <%= image_tag "https://api.dicebear.com/7.x/thumbs/svg?seed=#{current_user.email}&backgroundColor=0a5b83&shapeColor=69d2e7", class: "avatar-bordered-medium-shadow", alt: "avatar" %>
    <% end %>
  </div>

  <div class="px-3 text-center">
    <% if match.other(current_user).user.photo.attached? %>
      <%= image_tag(match.other(current_user).user.photo, class: "avatar-bordered-medium-shadow", alt: "avatar") %>
    <% else %>
       <%= image_tag "https://api.dicebear.com/7.x/thumbs/svg?seed=#{match.other(current_user).user.email}&backgroundColor=0a5b83&shapeColor=69d2e7", class: "avatar-bordered-medium-shadow", alt: "avatar" %>
    <% end %>
  </div>

  <div class="card-body d-flex flex-column">
    <h5 class="card-title">
      <%= "#{current_user.first_name.capitalize}'s & #{match.other(current_user).user.first_name.capitalize}'s Buddy dashboard" %>
    </h5>
    <p class="card-text">
      You can track your and your buddies' <strong><%= match.goal.category %> goal progress </strong> in this dashboard.
    </p>
    <span><%= link_to "Go to dashboard", match, class: "btn btn-primary align-self-end" %></span>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light px-3">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><i class="fa-solid fa-user-group me-3"></i>BuddyBoost</a>
    <%# <a class="navbar-brand" href="/">BuddyBoost</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto align-items-center">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= button_to(
                "Log out",
                destroy_user_session_path,
                method: :delete, class: "btn", id: "logout-btn") %>
            </li>
            <li class="nav-item">
              <a href="/profile">
                  <% if current_user.photo.attached? %>
                    <%= image_tag current_user.photo,
                      id: "navbarDropdown",
                      class: "avatar-bordered-small dropdown-toggle",
                      alt: "avatar"%>
                      <%# # data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <% else %>
                    <%= image_tag "https://api.dicebear.com/7.x/thumbs/svg?seed=#{current_user.email}&backgroundColor=0a5b83&shapeColor=69d2e7",
                      id: "navbarDropdown",
                      class: "avatar-bordered-small dropdown-toggle",
                      alt: "avatar"%>
                      <%# # data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
                  <% end %>
              </a>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: "btn", id: "login-btn" %>
            </li>
            <li class="nav-item">
              <%= link_to "Join us!", new_user_registration_path, class: "btn btn-primary", style:"background-color: #6587EB;"%>
            </li>
          <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_new-goal.html.erb
<div class="">
  <div class="mt-4 listing-form" data-controller="filter-subcategory">
    <%= simple_form_for(@goal) do |f| %>
      <%= f.input :category, as: :select, collection: Goal::CATEGORIES.keys,
                   input_html: { data: {action: "change->filter-subcategory#getKey"
                   }
                   }%>
      <%= f.input :sub_category, as: :select, collection: [],
                  input_html: { data: {filter_subcategory_target: "subcategory"} }   %>
      <%= f.input :description, label: "Describe your goal", required: true, placeholder: "For example: I really want to run a 5K in 25 minutes!" %>
      <%= f.error_notification message: "test" %>
      <%= f.full_error :confirmation_token %>
      <%= f.input :deadline  %>
      <%= f.label "Do you prefer meeting offline with your buddy, or online (or both)?", class: "py-3" %>
      <%= f.input :offline %>
      <%= f.input :online %>
      <%= f.submit "Add goal", class: "btn btn-primary my-4"%>
    <% end %>
  </div>
</div>

app/views/shared/_new-task.html.erb
<div class="">
  <div class="mt-4 listing-form">
    <%= simple_form_for([@match, @task]) do |f| %>
      <%= f.input :description, label: "What do you need to do to reach your goal?", placeholder: "Describe your to-do here!"%>
      <%= f.submit class: "btn btn-primary my-4"%>
    <% end %>
  </div>
</div>

app/views/shared/_profile-card.html.erb
<div id="profile-information" class="my-3" >

  <%# avatar  %>
  <div id="profile-avatar" class="py-3 pt-4 text-center">
    <% if current_user.photo.attached? %>
      <%= image_tag(current_user.photo, class: "avatar-bordered-large-shadow", alt: "avatar") %>
    <% else %>
      <%= image_tag "https://api.dicebear.com/7.x/thumbs/svg?seed=#{current_user.email}&backgroundColor=0a5b83&shapeColor=69d2e7", class: "avatar-bordered-large-shadow", alt: "avatar" %>
    <% end %>
    <div id="add-avatar-button">
      <%= link_to edit_user_registration_path do %>
          <i class="fas fa-pencil-alt ms-3"></i>
      <% end %>
    </div>
  </div>

  <%# profile info block + edit options %>
  <div id="profile-info" class="d-flex flex-column align-items-center pb-4">
    <li class="d-flex justify-content-between">
      <h3><%= current_user.first_name %> <%= current_user.last_name %></h3>
    </li>
    <li class="d-flex justify-content-between">
      <div><%= current_user.email %></div>
    </li>
  </div>

</div>

app/views/shared/_profile-tabs.html.erb
<ul class="nav nav-pills d-flex flex-column align-items-between" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link <%='active' if params[:location].nil?%>" id="profile-tab" data-bs-toggle="pill" data-bs-target="#profile-content" type="button" role="tab" aria-controls="profile-content" aria-selected="true">Profile</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link <%='active' if params[:location] == 'dashboards'%>" id="match-tab" data-bs-toggle="pill" data-bs-target="#matches" type="button" role="tab" aria-controls="matches" aria-selected="false">
      Dashboards
    </button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link <%='active' if params[:location] == 'goals'%>" id="goals-tab" data-bs-toggle="pill" data-bs-target="#goals" type="button" role="tab" aria-controls="goals" aria-selected="false">Goals</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link <%='active' if params[:location] == 'achievements'%>" id="achievements-tab" data-bs-toggle="pill" data-bs-target="#achievements" type="button" role="tab" aria-controls="achievements" aria-selected="false">Achievements</button>
  </li>
</ul>

app/views/shared/_task-list.html.erb
<li class="list-group-item list-group-item-light mb-1 task-list-item blue-background-no-p">
  <div class="custom-control custom-checkbox">

    <% if task.user == current_user %>

      <%= simple_form_for task, data: { turbo_frame: 'task-form' } do |f| %>
        <div class="d-flex align-items-center justify-content-between">
          <div class="d-flex align-items-center task-form-content">
            <small><%= f.input :status, as: :boolean, label: false, input_html: { onchange: 'this.form.submit()', id: "task_#{task.id}" } %></small>
            <label class="form-check-label" for="task_<%= task.id %>">
              <small><%= task.description %></small>
            </label>
          </div>
          <%= link_to delete_task_path(task),
                data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
            <i data-feather="trash-2" class="trash-icon-blue"></i>
          <% end %>
        </div>
    <% end %>

  <% else %>

   <%= simple_form_for task, data: { turbo_frame: 'task-form' } do |f| %>
    <div class="d-flex align-items-center task-form-content">
      <small><%= f.input :status, as: :boolean, label: false%></small>
      <label class="form-check-label" for="task_<%= task.id %>">
        <small><%= task.description %></small>
      </label>
    </div>
  <% end %>

  <% end %>

  </div>
</li>