config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :sessions => "custom_sessions" }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  root "pages#home"
  get '/legal', to: "pages#legal"
  get '/profile', to: "pages#profile"
  # get  '/my-achievements', to: "pages#my_achievements"

  resources :goals, only: [:create, :show, :index]

  resources :matches, only: [:show, :edit, :update, :index, :create] do
    resources :tasks, only: [:new, :create, :index]
    resources :chatrooms, only: [:show, :create] do
      resources :messages, only: :create
    end
  end

  resources :tasks, only: [:edit, :update]
  resources :tasks, only: :destroy, as: :delete_task
  resources :goals, only: [:edit, :update]
  resources :goals, only: :destroy, as: :delete_goal
end

app/models/match.rb
class Match < ApplicationRecord
  MATCH_STATUSES = ["in progress", "completed", "cancelled"]

  belongs_to :goal
  belongs_to :matched_goal, class_name: 'Goal'
  has_many :tasks
  has_one :chatroom

  def other(current_user)
    id = matched_goal.user.id == current_user.id ? goal.id : matched_goal.id
    Goal.find(id)
  end

  def set_status(status, cancel_reason)
    self.update(status: status, cancel_reason: cancel_reason)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!

  def index
    # matches only belongs to the current logged in user
    # @current_user_goal = Goal.where(user: current_user).where(match_id: params[:match_id])
    @matches = Match.where('goal_id IN (?) OR matched_goal_id IN (?)', current_user.goals.pluck(:id), current_user.goals.pluck(:id))
                    .where(status: 'in progress')
  end

  def show
    @match = Match.find(params[:id])
    @current_user_goal = Match.find(params[:id]).goal.user == current_user ? Match.find(params[:id]).goal : Match.find(params[:id]).matched_goal
     # for buddy dashboard tasks
    @my_tasks = Task.where(user: current_user).where(match: @match).order(created_at: :asc)
    @buddy_tasks = Task.where(match: @match).where.not(user: current_user).order(created_at: :asc)
    @task = Task.new

    # Calculate progress percentage - current user
    my_total_tasks = @my_tasks.count
    my_completed_tasks = @my_tasks.where(status: true).nil? ? 0 : @my_tasks.where(status: true).count
    @my_progress = my_total_tasks > 0 ? (my_completed_tasks.to_f / my_total_tasks) * 100 : 0

    # Calculate progress percentage - buddy of current user
    buddy_total_tasks = @buddy_tasks.count
    buddy_completed_tasks = @buddy_tasks.where(status: true).nil? ? 0 : @buddy_tasks.where(status: true).count
    @buddy_progress = buddy_total_tasks > 0 ? (buddy_completed_tasks.to_f / buddy_total_tasks) * 100 : 0

    @chatroom = @match.chatroom
    @chat = Chatroom.new
  end

  def edit
    find_match
  end

  def update
    find_match
    # @match.update(match_params)
    # redirect_to profile_path(current_user), notice: "Goal successfully created!"

    # update match status based on user selection (completed or cancelled)
    @match.set_status(params[:match][:status], params[:match][:cancel_reason])
    redirect_to profile_path(location: "achievements")

    # update goal status depending on match ending status
    if params[:match][:status] == 'completed'
      @match.goal.set_status('completed')
      @match.matched_goal.set_status('completed')
    else
      @match.goal.set_status('not started')
      @match.goal.set_unmatched
      @match.matched_goal.set_status('not started')
      @match.matched_goal.set_unmatched
    end
  end

  def create
    respond_to do |format|
      # Check how many in-progress matches the user has
      matches_current_number = Match.where('(goal_id IN (?) OR matched_goal_id IN (?)) AND status = (?)',
                                    current_user.goals.pluck(:id),
                                    current_user.goals.pluck(:id), 'in progress').count

      # Create a new record in the matches table or notify the user if the limit is reached
      if matches_current_number >= 3
        format.html{ redirect_to profile_path(location: "dashboards"), info: "You already have 3 buddies.
                                  We want you to focus first on them!
                                  You can see all your matches on your dashboard."
                   }

      else
        # Perform the matching logic here
        # Get the goal category user clicked on frontend w/ params[:match][:goal]
        clicked_goal_category = Goal.find(params[:match][:goal].to_i).category
        clicked_goal_subcategory = Goal.find(params[:match][:goal].to_i).sub_category

        # Find the first unmatched goal with the same category to make the match
        goal_id_sampled_by_subcategory = Goal.where(status: 'not started', matched: false)
                                             .where.not(user: current_user)
                                             .where(sub_category: clicked_goal_subcategory)
        goal_id_sampled_by_category = Goal.where(status: 'not started', matched: false)
                                          .where.not(user: current_user)
                                          .where(category: clicked_goal_category)

        if goal_id_sampled_by_category.empty? && goal_id_sampled_by_subcategory.empty?
          format.html { redirect_to profile_path(location: "goals"),
                        info: 'No match yet! There is no available buddy at this moment with a similar goal. Match a different goal or try again later.' }
        else
          matched_goal_id = goal_id_sampled_by_subcategory.empty? ? goal_id_sampled_by_category.sample.id : goal_id_sampled_by_subcategory.sample.id
          # create the match as we now goal and matched_goal
          @match = Match.new
          @match.goal = Goal.find(params[:match][:goal].to_i)
          @goal = @match.goal
          @match.matched_goal = Goal.find(matched_goal_id)
          @match.save
          # Update the goal status and matched=true after match is created!
          @match.goal.set_status('in progress')
          @match.goal.set_matched
          @match.matched_goal.set_status('in progress')
          @match.matched_goal.set_matched
          format.html { redirect_to profile_path(location: "dashboards"), info: "Successfully matched with
                       #{@match.matched_goal.user.first_name}! Go to your buddy dashboard to support each other 💪"
                      }
        end
      end
    end
  end

  private

  def match_params
    params.require(:match).permit(:status, :cancel_reason)
  end

  def find_match
    @id = params[:id]
    @match = Match.find(params[:id])
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_create_match.html.erb
<p>Creating a match for the goal <%= goal.category %></p>
<p>Match is created <%= match.id  %></p>

app/views/matches/_match-card.html.erb
<div class="card d-flex flex-row">
  <%  %>
  <div id="profile-avatar" class="px-3 text-center">
    <% if current_user.photo.attached? %>
      <%= image_tag(current_user.photo, class: "avatar-bordered-small-shadow", alt: "avatar", style: "width: 150px; height: 150px; object-fit: cover;") %>
    <% else %>
       <%= image_tag "avatar_default.svg", class: "avatar-bordered-small-shadow", alt: "avatar", style: "width: 150px; height: 150px; object-fit: cover;" %>
    <% end %>
  </div>
  <div id="profile-avatar" class="px-3 text-center">
    <% if match.matched_goal.user.photo.attached? %>
      <%= image_tag(match.matched_goal.user.photo, class: "avatar-bordered-small-shadow", alt: "avatar", style: "width: 150px; height: 150px; object-fit: cover;") %>
    <% else %>
       <%= image_tag "avatar_default.svg", class: "avatar-bordered-small-shadow", alt: "avatar", style: "width: 150px; height: 150px; object-fit: cover;" %>
    <% end %>
  </div>
      <div class="card-body">
      <h5 class="card-title"><%= "#{match.matched_goal.user.first_name}'s & #{match.goal.user.first_name}'s Buddy Dashboard" %></h5>
      <p class="card-text">You can track your and <%= match.matched_goal.user.first_name %>'s <strong><%= match.goal.category %></strong> goal progress in this dashboard.</p>
      <%= link_to "Go Dashboard", match, class: "btn btn-primary" %>
    </div>
</div>

app/views/matches/edit.html.erb
<h2>Empty page :)</h2>

app/views/matches/index.html.erb
<h2>Buddy Dashboards</h2>
<div class="d-flex justify-content-between align-items-start">
  <div class="list-card-container list-index">
       <% @matches.each do |match| %>
        <%= render "shared/match-card", match: match %>
      <% end %>
  </div>
</div>

app/views/matches/show.html.erb
<%# container for all dashboard content %>
<div class="row d-flex justify-content-center w-100 mt-2" id="buddy-dash">

  <%# ---------------- FIRST COLUMN ------------ %>

  <div class="col-3 blue-background d-flex flex-column justify-content-between mt-3 column-dash">

    <%# ---------------- 1. HEADING & AVATARS -------------------- %>

    <div class="text-center mt-3">

      <h4><%= "Buddy Dashboard of #{current_user.first_name.capitalize} & #{@match.other(current_user).user.first_name.capitalize}" %>  </h4>

      <div class="d-flex justify-content-center my-4 flex-wrap">
        <div id="profile-avatar" class="px-3">
          <% if current_user.photo.attached? %>
            <%= image_tag(current_user.photo, class: "avatar-bordered-medium-shadow", alt: "avatar") %>
          <% else %>
            <%= image_tag "https://api.dicebear.com/7.x/thumbs/svg?seed=#{current_user.email}&backgroundColor=0a5b83&shapeColor=69d2e7", class: "avatar-bordered-medium-shadow", alt: "avatar" %>
          <% end %>
        </div>
        <div id="profile-avatar" class="px-3">
          <% if @match.other(current_user).user.photo.attached? %>
            <%= image_tag(@match.other(current_user).user.photo, class: "avatar-bordered-medium-shadow", alt: "avatar") %>
          <% else %>
            <%= image_tag "https://api.dicebear.com/7.x/thumbs/svg?seed=#{@match.other(current_user).user.email}&backgroundColor=0a5b83&shapeColor=69d2e7", class: "avatar-bordered-medium-shadow", alt: "avatar" %>
          <% end %>
        </div>
      </div>

    </div>

    <%# ------------------ 2. BUTTONS ------------------------  %>
    <div class="d-flex flex-column">

      <%# <!-- Chat button --> %>
      <%# if chatroom of the match is nil, then create a new chatroom %>

      <% if @chatroom.nil?  %>
        <%= simple_form_for @chat, url: match_chatrooms_path(@match) do |f| %>
          <%= f.input :match_id, as: :hidden, input_html: { value: @match.id } %>
          <%= f.input :sender_id, as: :hidden, input_html: { value: current_user.id } %>
          <%= f.input :receiver_id, as: :hidden, input_html: { value: @match.matched_goal.user.id } %>
          <%= f.button :submit, "Chat with your buddy! 💬", class: "btn white-background-shadow-blue-hover text-center w-100" %>

        <% end %>
      <% else %>
        <%= link_to "Chat with your buddy! 💬", match_chatroom_path(@match, @chatroom), class: "btn white-background-shadow-blue-hover text-center w-100" %>
      <% end %>

      <%# complete button  %>
      <%= simple_form_for @match, method: :put do |f| %>
        <%= f.input :status, label: false, field: false, input_html: { style: "display: none", value: "completed" }%>
        <%= f.button :submit, "Complete buddy match", class: "btn white-background-shadow-blue-hover w-100",
        data: {controller: "confetti", action: "mousedown->confetti#spray", confetti_animation_value: "school-pride",
        confetti_duration_value: 3, confetti_follow_value: false }%>
      <% end %>
 <%# %>
      <!-- Button trigger modal to update match status -->
      <button type="button" class="btn op-white-background-shadow-blue-hover mt-3 p-0" data-toggle="modal" data-target="#updateMatchModalCenter">
        <small class="d-flex align-items-center justify-content-center"><i class="fa-solid fa-xmark me-2"></i> cancel buddy match</small>
      </button>

        <!-- Modal to update match status -->
        <div class="modal fade" id="updateMatchModalCenter" tabindex="-1" role="dialog" aria-labelledby="updateMatchStatus" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="updateMatchModalTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <%= render "shared/edit-match-form" %>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>
  <%# end column 1  %>

  <%# ---------------- SECOND COLUMN: BUDDY 1 (CURRENT_USER) ------------ %>

  <div class="col-4 gray-background mx-3 mt-3 column-dash">

    <%# ----------------- goal information ---------------------  %>
    <div>
      <div class="white-background-dash">
        <p class=><strong><%= current_user.first_name.capitalize %>'s goal:</strong> <%= @current_user_goal.description %> </p>
        <div class="progress" style="height: 30px;">
          <div class="progress-bar p-3" role="progressbar" style="width : <%=@my_progress.round(2)%>%" aria-valuenow="<%= @my_progress.round(2) %>" aria-valuemin="0" aria-valuemax="100"> <%= @my_progress.round(2) %>% </div>
        </div>
      </div>
      <div class="mt-3">
        <small>
          <ul class="list-group list-group-flush" >
            <li class="list-group-item"><strong>Category:</strong> <%=  @current_user_goal.category %></li>
            <li class="list-group-item"><strong>Subcategory: </strong><%= @current_user_goal.sub_category %></li>
            <li class="list-group-item"><strong>Deadline:</strong> <%= @current_user_goal.deadline %></li>
          </ul>
        </small>
      </div>
    </div>

    <%# ---------------- TASKS ------------------- %>
    <div class="white-background-dash-noflex mt-3">

      <p><strong><%= current_user.first_name.capitalize %>'s</strong> tasks</p>
      <div>
        <ul class="list-group list-group-flush task-list-scrollable">
          <% @my_tasks.each do |task| %>
              <%= render "shared/task-list", task: task %>
          <% end %>
        </ul>
      </div>

      <!-- Button trigger modal -->
      <div class="d-flex align-items-center justify-content-center">
        <button type="button" class="btn create-task-button mt-2" data-toggle="modal" data-target="#newTaskModalCenter">
          <i class="fa-solid fa-plus"></i> Add new task
        </button>
      </div>

      <!-- Modal -->
      <div class="modal fade" id="newTaskModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle"></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <%= render "shared/new-task" %>
            </div>
          </div>
        </div>
      </div>

    </div>
  <%# end column  %>
  </div>

  <%# ---------------- THIRD COLUMN: BUDDY ------------ %>

  <div class="col-4 gray-background mt-3 column-dash">

    <%# ----------------- goal information ---------------------  %>
    <div>
      <div class="white-background-dash mb-3">
        <p class=""><strong><%= @match.other(current_user).user.first_name.capitalize %>'s goal:</strong> <%= @match.other(current_user).description %> </p>
        <div class="progress" style="height: 30px;">
          <div class="progress-bar p-3" role="progressbar" style="width : <%=@buddy_progress.round(2)%>%" aria-valuenow="<%= @buddy_progress.round(2)%>" aria-valuemin="0" aria-valuemax="100"> <%= @buddy_progress.round(2)%>% </div>
        </div>
      </div>
      <div class="mt-3">
        <small>
          <ul class="list-group list-group-flush" >
            <li class="list-group-item"><strong>Category:</strong> <%= @match.other(current_user).category %> </li>
            <li class="list-group-item"><strong>Subcategory: </strong><%= @match.other(current_user).sub_category %> </li>
            <li class="list-group-item"><strong>Deadline:</strong> <%= @match.other(current_user).deadline %> </li>
          </ul>
        </small>
      </div>
    </div>

    <%# ---------------- TASKS ------------------- %>

    <div class="white-background-dash-noflex mt-3">
      <p class=""> <strong><%= @match.other(current_user).user.first_name.capitalize %>'s</strong> tasks </p>

      <div>
        <% if @buddy_tasks.length == 0 %>
          <div class="d-flex align-items-center justify-content-center">
            <p class="mt-2"><small><%= @match.other(current_user).user.first_name.capitalize %> has not added any tasks yet.</small></p>
          </div>
        <% else %>
          <% @buddy_tasks.each do |task| %>
            <ul class="list-group">
              <%= render "shared/task-list", task: task %>
            </ul>
          <% end %>
        <% end %>
      </div>


    </div>

  </div>

  <%# end column 3  %>

</div>